// <auto-generated />
using System;
using ClangLogAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClangLogAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260628182132_SeedExerciseCatalog")]
    partial class SeedExerciseCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClangLogAPI.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("MuscleGroup")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Barbell press from a flat bench",
                            MuscleGroup = "Chest",
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Barbell press from an inclined bench",
                            MuscleGroup = "Chest",
                            Name = "Incline Bench Press"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Barbell back squat",
                            MuscleGroup = "Legs",
                            Name = "Squat"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Machine leg press",
                            MuscleGroup = "Legs",
                            Name = "Leg Press"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Conventional barbell deadlift",
                            MuscleGroup = "Back",
                            Name = "Deadlift"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Bent-over barbell row",
                            MuscleGroup = "Back",
                            Name = "Barbell Row"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Bodyweight pull up",
                            MuscleGroup = "Back",
                            Name = "Pull Up"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Standing barbell overhead press",
                            MuscleGroup = "Shoulders",
                            Name = "Overhead Press"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Dumbbell or barbell bicep curl",
                            MuscleGroup = "Arms",
                            Name = "Bicep Curl"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Cable tricep pushdown",
                            MuscleGroup = "Arms",
                            Name = "Tricep Pushdown"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Isometric core hold",
                            MuscleGroup = "Core",
                            Name = "Plank"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Bodyweight or weighted lunges",
                            MuscleGroup = "Legs",
                            Name = "Lunges"
                        });
                });

            modelBuilder.Entity("ClangLogAPI.Models.ExerciseSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Repetitions")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric");

                    b.Property<int?>("WeightUnit")
                        .HasColumnType("integer");

                    b.Property<int>("WorkoutExerciseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutExerciseId");

                    b.ToTable("ExerciseSets");
                });

            modelBuilder.Entity("ClangLogAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ClangLogAPI.Models.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CaloriesBurned")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("ClangLogAPI.Models.WorkoutExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutExercises");
                });

            modelBuilder.Entity("ClangLogAPI.Models.ExerciseSet", b =>
                {
                    b.HasOne("ClangLogAPI.Models.WorkoutExercise", "WorkoutExercise")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutExercise");
                });

            modelBuilder.Entity("ClangLogAPI.Models.Workout", b =>
                {
                    b.HasOne("ClangLogAPI.Models.User", "User")
                        .WithMany("Workouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClangLogAPI.Models.WorkoutExercise", b =>
                {
                    b.HasOne("ClangLogAPI.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClangLogAPI.Models.Workout", "Workout")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("ClangLogAPI.Models.User", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("ClangLogAPI.Models.Workout", b =>
                {
                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("ClangLogAPI.Models.WorkoutExercise", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
